DROP TABLE IF EXISTS TB_TRADE;

CREATE TABLE TB_TRADE (
    TR_DATE VARCHAR(8) NOT NULL,
    ACCT_NO VARCHAR(8) NOT NULL,
    TR_NO NUMERIC(16) NOT NULL,
    TR_AMT NUMERIC(16) NOT NULL,
    TR_FEE NUMERIC(16) NOT NULL,
    CANCEL_YN VARCHAR(1) NOT NULL,
    PRIMARY KEY (TR_DATE, ACCT_NO, TR_NO)
) as SELECT * FROM CSVREAD('classpath:Data_Trade.csv', null, 'charset=UTF-8');


DROP TABLE IF EXISTS TB_INFO_ACCT;

CREATE TABLE TB_INFO_ACCT (
    ACCT_NO VARCHAR(8) NOT NULL,
    ACCT_NM VARCHAR(100) NOT NULL,
    BKR_CD VARCHAR(1) NOT NULL,
    PRIMARY KEY (ACCT_NO)
) as SELECT * FROM CSVREAD('classpath:Data_Acct.csv', null, 'charset=UTF-8');


DROP TABLE IF EXISTS TB_INFO_BKR;

CREATE TABLE TB_INFO_BKR (
    BKR_CD VARCHAR(1) NOT NULL,
    BKR_NM VARCHAR(100) NOT NULL,
    PRIMARY KEY (BKR_CD)
) as SELECT * FROM CSVREAD('classpath:Data_Bkr.csv', null, 'charset=UTF-8');